import os

CLAN_TAG = os.getenv("CLAN_TAG", "GAL")
CLAN_DISPLAY = f"[{CLAN_TAG}]"
MERGE_PREFIXES = [
    p.strip().upper()
    for p in os.getenv("LEADERBOARD_MERGE_PREFIXES", "PRINCE,ELP").split(",")
    if p.strip()
]

TOKEN = os.getenv("DISCORD_TOKEN") or os.getenv("DISCORD_BOT_TOKEN")
GUILD_ID = os.getenv("DISCORD_GUILD_ID")
DB_URL = (
    os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("POSTGRESQL_URL")
)

API_BASE = "https://api.openfront.io/public"
USER_AGENT = "Mozilla/5.0 (GauloisBot/1.1)"
OPENFRONT_API_KEY = os.getenv("OPENFRONT_API_KEY")
OPENFRONT_GAME_URL_TEMPLATE = os.getenv(
    "OPENFRONT_GAME_URL_TEMPLATE",
    "https://openfront.io/w3/game/{game_id}?live",
)
ONEV1_LEADERBOARD_URL = os.getenv(
    "OPENFRONT_1V1_LEADERBOARD_URL",
    "https://api.openfront.io/leaderboard/ranked",
)

REFRESH_MINUTES = int(os.getenv("LEADERBOARD_REFRESH_MINUTES", "30"))
RANGE_HOURS = int(os.getenv("LEADERBOARD_RANGE_HOURS", "24"))
MAX_SESSIONS = int(os.getenv("LEADERBOARD_MAX_SESSIONS", "300"))
BACKFILL_START = os.getenv("LEADERBOARD_BACKFILL_START", "2026-01-01T00:00:00Z")
BACKFILL_INTERVAL_MINUTES = int(os.getenv("LEADERBOARD_BACKFILL_INTERVAL_MINUTES", "5"))
MIN_GAMES = int(os.getenv("LEADERBOARD_MIN_GAMES", "10"))
PRIOR_GAMES = int(os.getenv("LEADERBOARD_PRIOR_GAMES", "50"))
ONEV1_BACKFILL_START = os.getenv("LEADERBOARD_1V1_BACKFILL_START", "2026-01-01T00:00:00Z")
ONEV1_BACKFILL_INTERVAL_MINUTES = int(os.getenv("LEADERBOARD_1V1_BACKFILL_INTERVAL_MINUTES", "10"))
ONEV1_MAX_GAMES = int(os.getenv("LEADERBOARD_1V1_MAX_GAMES", "200"))
ONEV1_REFRESH_MINUTES = int(os.getenv("LEADERBOARD_1V1_REFRESH_MINUTES", "60"))
SCORE_RATIO_WEIGHT = float(os.getenv("LEADERBOARD_SCORE_RATIO_WEIGHT", "100"))
SCORE_GAMES_WEIGHT = float(os.getenv("LEADERBOARD_SCORE_GAMES_WEIGHT", "0.1"))

WIN_NOTIFY_CHANNEL_ID = os.getenv("WIN_NOTIFY_CHANNEL_ID")
WIN_NOTIFY_POLL_SECONDS = int(os.getenv("WIN_NOTIFY_POLL_SECONDS", "300"))
WIN_NOTIFY_RANGE_HOURS = int(os.getenv("WIN_NOTIFY_RANGE_HOURS", "24"))
WIN_NOTIFY_EMPTY_COOLDOWN_MINUTES = int(os.getenv("WIN_NOTIFY_EMPTY_COOLDOWN_MINUTES", "60"))

OFM_ROLE_ID = int(os.getenv("OFM_ROLE_ID", "1469695783790968963"))
OFM_MANAGER_ROLE_ID = int(os.getenv("OFM_MANAGER_ROLE_ID", "1469701081759219723"))
OFM_TEAM_ROLE_ID = int(os.getenv("OFM_TEAM_ROLE_ID", "1469701766223368216"))
OFM_LEADER_ROLE_ID = int(os.getenv("OFM_LEADER_ROLE_ID", "0"))
OFM_SUB_ROLE_ID = int(os.getenv("OFM_SUB_ROLE_ID", "0"))
OFM_CATEGORY_ID = int(os.getenv("OFM_CATEGORY_ID", "1469703934514827531"))
OFM_BOARD_CHANNEL_ID = int(os.getenv("OFM_BOARD_CHANNEL_ID", "1469696688804466972"))
OFM_ADMIN_CHANNEL_ID = int(os.getenv("OFM_ADMIN_CHANNEL_ID", "1469711880565162201"))
ADMIN_PANEL_CHANNEL_ID = int(os.getenv("ADMIN_PANEL_CHANNEL_ID", "1469724972246237436"))
MOD_LOG_CHANNEL_ID = int(os.getenv("MOD_LOG_CHANNEL_ID", "1351168832261193791"))
FOUNDER_USER_ID = int(os.getenv("FOUNDER_USER_ID", "1350921590359195699"))
ADMIN_USER_ID = int(os.getenv("ADMIN_USER_ID", "1351313848275042385"))

MOD_COMMANDS = [
    "warn",
    "warnlist",
    "clearwarn",
    "mute",
    "kick",
    "ban",
    "unban",
    "case",
    "note",
]

if RANGE_HOURS > 48:
    RANGE_HOURS = 48
if RANGE_HOURS < 1:
    RANGE_HOURS = 1
if REFRESH_MINUTES < 5:
    REFRESH_MINUTES = 5
if MAX_SESSIONS < 50:
    MAX_SESSIONS = 50
if MAX_SESSIONS > 1000:
    MAX_SESSIONS = 1000
if BACKFILL_INTERVAL_MINUTES < 5:
    BACKFILL_INTERVAL_MINUTES = 5
if MIN_GAMES < 1:
    MIN_GAMES = 1
if PRIOR_GAMES < 1:
    PRIOR_GAMES = 1
if ONEV1_BACKFILL_INTERVAL_MINUTES < 5:
    ONEV1_BACKFILL_INTERVAL_MINUTES = 5
if ONEV1_MAX_GAMES < 10:
    ONEV1_MAX_GAMES = 10
if ONEV1_MAX_GAMES > 1000:
    ONEV1_MAX_GAMES = 1000
if ONEV1_REFRESH_MINUTES < 10:
    ONEV1_REFRESH_MINUTES = 10
if WIN_NOTIFY_POLL_SECONDS < 60:
    WIN_NOTIFY_POLL_SECONDS = 60
if WIN_NOTIFY_RANGE_HOURS < 1:
    WIN_NOTIFY_RANGE_HOURS = 1
if WIN_NOTIFY_RANGE_HOURS > 48:
    WIN_NOTIFY_RANGE_HOURS = 48
if WIN_NOTIFY_EMPTY_COOLDOWN_MINUTES < 1:
    WIN_NOTIFY_EMPTY_COOLDOWN_MINUTES = 1
